singleQuote: false
printWidth: 80
tabWidth: 2
useTabs: false
semi: true
indent: 2
no_ensure_ascii: false
no_sort_keys: false
top_keys: []
trailingComma: "none"
bracketSpacing: true
arrowParens: "avoid"
parser: "yaml"
overrides:
  - files: "*.yaml"
    options:
      singleQuote: false
      printWidth: 80
      tabWidth: 2
      useTabs: false
      semi: true
      trailingComma: "none"
      bracketSpacing: true
      arrowParens: "avoid"
