---
repos:
  # Built-in hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # ShellCheck hook for linting shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: ""
    hooks:
      - id: shellcheck
        name: shellcheck
        description: This hook runs shellcheck for linting shell scripts
  # Bashate hook for linting shell scripts
  - repo: https://github.com/openstack/bashate
    rev: ""
    hooks:
      - id: bashate
        name: bashate
        description: This hook runs bashate for linting shell scripts
        entry: bashate
        language: python
        types: [shell]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: ""
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
  - repo: https://github.com/rhysd/actionlint
    rev: ""
    hooks:
      - id: actionlint
  - repo: https://github.com/google/yamlfmt
    rev: ""
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: ""
    hooks:
      - id: yamllint
