repos:
  # Built-in hook
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ""
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  # ShellCheck hook for linting shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: ""
    hooks:
      - id: shellcheck
        name: shellcheck
        description: This hook runs shellcheck for linting shell scripts
  # Bashate hook for linting shell scripts
  - repo: https://github.com/openstack/bashate
    rev: ""
    hooks:
      - id: bashate
        name: bashate
        description: This hook runs bashate for linting shell scripts
        entry: bashate
        language: python
        types: [shell]
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: ""
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]
  - repo: https://github.com/rhysd/actionlint
    rev: ""
    hooks:
      - id: actionlint
  - repo: https://github.com/google/yamlfmt
    rev: ""
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: ""
    hooks:
      - id: yamllint
  - repo: https://github.com/codespell-project/codespell
    rev: ""
    hooks:
    - id: codespell
  - repo: https://github.com/mrtazz/checkmake
    rev: ""
    hooks:
      - id: checkmake
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: ""
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix
  - repo: https://github.com/bufbuild/buf
    rev: ""
    hooks:
      - id: buf-generate
      - id: buf-breaking
      - id: buf-lint
      - id: buf-format
      - id: buf-dep-update
      - id: buf-dep-prune
      - id: buf-mod-update
      - id: buf-mod-prune
  - repo: https://github.com/rubocop/rubocop
    rev: ""
    hooks:
      - id: rubocop
  - repo: https://github.com/AleksaC/terraform-py
    rev: ""
    hooks:
      - id: tf-fmt
      - id: tf-validate
  - repo: https://github.com/realm/SwiftLint
    rev: ""
    hooks:
      - id: SwiftLint
  - repo: https://github.com/gitleaks/gitleaks
    rev: ""
    hooks:
      - id: gitleaks
  - repo: https://github.com/thoughtworks/talisman
    rev: ""
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
  - repo: https://github.com/crate-ci/typos
    rev: ""
    hooks:
      - id: typos
      - id: typos-docker
      - id: typos-src
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: ""
    hooks:
      - id: clang-format
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: ""
    hooks:
      - id: eslint